version: '3.5'
services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: legalbot_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - legalbot_qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  backend:

volumes:
  legalbot_qdrant_storage:
